### ISSUE TITLE
Something is wrong here

### ISSUE THREAD

**Issue by Evyay** [Evyay/Flashy#1]
```go
valuelen := int(binary.LittleEndian.Uint64(valuelenbyt))
```

2015/03/31 23:32:49 http: panic serving 127.0.0.1:63168: runtime error: index out of range
goroutine 140 [running]:
net/http.func·011()
	/usr/local/go/src/net/http/server.go:1130 +0xbb
encoding/binary.littleEndian.Uint64(0xc21299e000, 0x0, 0x0, 0x0)
	/usr/local/go/src/encoding/binary/binary.go:71 +0x11c
main.database.write(0xc2080adb80, 0x44d540, 0x7, 0xc209cbc150, 0xc2080ac600, 0x0, 0x0)
	/Users/lukas/Development/Goworkspace/src/evyay.com/Flashy/operations.go:134 +0x4ab3
main.handler(0x7263c0, 0xc20933e640, 0xc208032c30)
	/Users/lukas/Development/Goworkspace/src/evyay.com/Flashy/handler.go:108 +0xe49
net/http.HandlerFunc.ServeHTTP(0x507bc0, 0x7263c0, 0xc20933e640, 0xc208032c30)
	/usr/local/go/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc20803a900, 0x7263c0, 0xc20933e640, 0xc208032c30)
	/usr/local/go/src/net/http/server.go:1541 +0x17d
net/http.serverHandler.ServeHTTP(0xc208036480, 0x7263c0, 0xc20933e640, 0xc208032c30)
	/usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc20f102140)
	/usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e

**Comment by Evyay** [comment]
Seems to be fixed.
